apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: my-namespace
  labels:
    env: prod1
spec:
  containers:
  - name: container-nginx
    image: nginx
  - name: container-redis
    image: redis